#!/usr/bin/bash

# =================函数=====================

# cd到工作目录
function cdw()
{
	if [ -d ~/working ]; then
		cd ~/working
	else
		mkdir ~/working
		cd ~/working
	fi
}

# cd到python虚拟环境目录
function cdenv()
{
	if [ -d ~/.allenv ]; then
		cd ~/.allenv
	else
		mkdir ~/.allenv
		cd ~/.allenv
	fi
}

# 创建python虚拟环境，并添加别名
# function myvirtualenv()
# {
# 	virtualenv=$(which virtualenv)
# 	# 字符串比较时，最好使用双中括号
# 	[[ -n $@ ]] && virtualenv $@
# 	success=$?

# 	# 获取命令行的最后一个元素
# 	for last in $@; do
# 		true
# 	done

# 	# 判断命令是否执行成功，成功则写入别名
# 	if [ $success -eq 0 ] && [ -e ~/.allenv/$last ]; then
# 		cat >> ~/.virtualenv_alias <<EOF
# alias env-$last="source ~/.allenv/$last/bin/activate"
# EOF
# 	fi
# }

# [ -e ~/.virtualenv_alias ] && source ~/.virtualenv_alias




# ===============别名设置========================

alias py="python"
alias p3="python3"
alias cdd="cd ~/Desktop"